import type { Metadata } from "next";
import "./globals.css";
import MegamartNavbar from "@/components/nav";
import Toast from "@/components/toast";
import Loading from "@/components/loading";
export const metadata: Metadata = {
  title: "MegaMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head >
        <link rel="icon" href="/zap.svg" />
      </head>
      <body>
        <nav>
          <MegamartNavbar />
        </nav>
        <Toast />
        {children}
      </body>
    </html>
  );
}
