import type { Metadata } from "next";
import "./globals.css";
import MegamartNavbar from "@/components/nav";

export const metadata: Metadata = {
  title: "MegaMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <MegamartNavbar />
        </nav>
        {children}
      </body>
    </html>
  );
}
